{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andreidurlea",
    "module": "corecontrol",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0.aar",
          "url": "corecontrol-1.1.0.aar",
          "size": 131140,
          "sha512": "25bfb5f9bb4b768cf77d0fdb199b7585a908ea8884ca42715e08100b482b5e345031c6d0795bb1dcb06a588b208ee21c60a589e48d86f173647d9e81f26c956d",
          "sha256": "f7af1732ae28797c8283c2d0877ae65f97c3b4e170d3d658139a6a63ac9a7f08",
          "sha1": "1d9522ef90a60485a253cae49b27957ab5a18816",
          "md5": "a8902f4041f03c16c42cc58ec363f1ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0.aar",
          "url": "corecontrol-1.1.0.aar",
          "size": 131140,
          "sha512": "25bfb5f9bb4b768cf77d0fdb199b7585a908ea8884ca42715e08100b482b5e345031c6d0795bb1dcb06a588b208ee21c60a589e48d86f173647d9e81f26c956d",
          "sha256": "f7af1732ae28797c8283c2d0877ae65f97c3b4e170d3d658139a6a63ac9a7f08",
          "sha1": "1d9522ef90a60485a253cae49b27957ab5a18816",
          "md5": "a8902f4041f03c16c42cc58ec363f1ea"
        }
      ]
    }
  ]
}
