{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andreidurlea",
    "module": "corecontrol",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0.aar",
          "url": "corecontrol-1.1.0.aar",
          "size": 131084,
          "sha512": "0fcdd60cd6e008b09f434a5ef8874d9224aa457712ae69551f5f6aca47288784a1289ca3620a9ac2977e36cbfa08c75062b47c78391dc30d3f7fdebfde9fb4b3",
          "sha256": "c892e1eefd6a9c3d29aa706ed9525305935b68d0a94e8eaba3f4abf64655c55b",
          "sha1": "288aa53aea2772db333de71c6bb0629bf6e7d970",
          "md5": "c0d466de80c7ac5efe4b544118928139"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0.aar",
          "url": "corecontrol-1.1.0.aar",
          "size": 131084,
          "sha512": "0fcdd60cd6e008b09f434a5ef8874d9224aa457712ae69551f5f6aca47288784a1289ca3620a9ac2977e36cbfa08c75062b47c78391dc30d3f7fdebfde9fb4b3",
          "sha256": "c892e1eefd6a9c3d29aa706ed9525305935b68d0a94e8eaba3f4abf64655c55b",
          "sha1": "288aa53aea2772db333de71c6bb0629bf6e7d970",
          "md5": "c0d466de80c7ac5efe4b544118928139"
        }
      ]
    }
  ]
}
