{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andreidurlea",
    "module": "corecontrol",
    "version": "1.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0-beta.aar",
          "url": "corecontrol-1.1.0-beta.aar",
          "size": 130851,
          "sha512": "ae8f2507afa75049e1c692f034cee81c7d3e3500bc3d5987b176ccaf0c7c76f5ba4afa6562a419e2953e53f79da29a39375fcc284d04490218999bd869d91110",
          "sha256": "6a3f6d5d7d51339997ff27316e314504e63ad0d6d113196dd277531958d64a83",
          "sha1": "c626d38d2438c8d40141287f1245673f5f272bae",
          "md5": "af4a556de9922000152dc0541acd16b9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.1.0-beta.aar",
          "url": "corecontrol-1.1.0-beta.aar",
          "size": 130851,
          "sha512": "ae8f2507afa75049e1c692f034cee81c7d3e3500bc3d5987b176ccaf0c7c76f5ba4afa6562a419e2953e53f79da29a39375fcc284d04490218999bd869d91110",
          "sha256": "6a3f6d5d7d51339997ff27316e314504e63ad0d6d113196dd277531958d64a83",
          "sha1": "c626d38d2438c8d40141287f1245673f5f272bae",
          "md5": "af4a556de9922000152dc0541acd16b9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "corecontrol-1.1.0-beta-sources.jar",
          "url": "corecontrol-1.1.0-beta-sources.jar",
          "size": 95739,
          "sha512": "2959a7ef721ffdeb80634b03c1dfdee6fedcf80ca9ae7168d994a159aeb49abc3cd5bef7b81c6b2bf89e56494079d89b6203f87ee6f0242a65a5ea6f8dc85fc3",
          "sha256": "15777375957e84e0e976dfdcacd4c4a5717384ff67877a4eaa878721a992a29a",
          "sha1": "b0f8b2e5d909e6077c6e60932047b5c79226a108",
          "md5": "27ae648e3dd1eee3b865d3bd82d87909"
        }
      ]
    }
  ]
}
